version: '3'
services:
  nginx1:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - D:\Kerja\Politeknik Negeri Padang\Perkuliahan\Rabu 3MI-3C Micro Service\Catatan\3MI_3C_-Mikro-service\docker_volume\html1:/usr/share/nginx/html
  nginx2:
    image: nginx
    ports:
      - "8081:80"
    volumes:
      - D:\Kerja\Politeknik Negeri Padang\Perkuliahan\Rabu 3MI-3C Micro Service\Catatan\3MI_3C_-Mikro-service\docker_volume\html1:/usr/nginx/html
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: "coba123"
      MYSQL_ROOT_PASSWORD: "12345678"
      MYSQL_ROOT_HOST: "%"
    volumes:
      - D:\Kerja\Politeknik Negeri Padang\Perkuliahan\Rabu 3MI-3C Micro Service\Catatan\3MI_3C_-Mikro-service\docker_volume\mysql_data:/var/lib/mysql
    networks:
      - network1
  phpmyadmin:
    image: phpmyadmin
    ports: 
      - "8082:80"
    environment:
      PMA_HOST: mysql
    networks:
      - network1
networks:
  network1:
    driver: bridge

       

